[package]
name = "neptune-triton-generator"
description = "Generate code for neptune-triton from Futhark source."
version = "1.1.0"
authors = ["porcuquine <porcuquine@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/filecoin-project/neptune-triton/tree/master/library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genfut = { version = "0.2.1", default-features = false, features = ["opencl"] }

[[bin]]
name="codegen"

